[tool.black]
color = true

[tool.coverage.run]
source = ["{{module}}"]

[tool.coverage.report]
show_missing = true

[tool.pytest.ini_options]
addopts = "--color=yes --doctest-modules --verbose"

[tool.ruff]
extend-select = ["B", "BLE", "C4", "C90", "COM", "DJ", "DTZ", "EM", "G", "I", "N", "PIE", "PL", "PT", "PTH", "R", "S", "SIM", "T10", "TID", "W", "YTT"]

[tool.ruff.per-file-ignores]
"tests/*.py" = ["S101"]
