[tool.bandit]
exclude_dirs = [".git",".github",".tox","examples","tests"]
skips = ["B404","B602"]

[tool.black]
color = true

[tool.coverage.run]
source = ["cli_test_helpers"]

[tool.coverage.report]
show_missing = true

[tool.isort]
color_output = true
profile = "black"
skip_glob = ["examples/*.py"]

[tool.pylint.master]
disable = ["super-with-arguments"]
output-format = "colorized"

[tool.pytest.ini_options]
addopts = "--color=yes --doctest-modules --ignore examples/ --junitxml=tests/junit-report.xml --verbose"

[tool.ruff]
extend-exclude = ["examples"]
extend-select = ["B", "BLE", "C4", "C90", "COM", "DJ", "DTZ", "EM", "G", "I", "N", "PIE", "PL", "PT", "PTH", "R", "S", "SIM", "T10", "TID", "W", "YTT"]

[tool.ruff.per-file-ignores]
"cli_test_helpers/commands.py" = ["S602"]
"setup.py" = ["PTH"]
"tests/*.py" = ["S101"]
