name: Checks

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

env:
  PIP_DISABLE_PIP_VERSION_CHECK: '1'
  PY_COLORS: '1'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
        - lint
        - format
        - package
        - docs
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install prerequisites
      run: python -m pip install tox
    - name: Run ${{ matrix.env }}
      run: tox -e ${{ matrix.env }}
