name: Checks

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

env:
  PIP_DISABLE_PIP_VERSION_CHECK: '1'
  PY_COLORS: '1'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
        - ruff
        - example-argparse
        - example-click
        - example-docopt
        - package
        - docs
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install prerequisites
      run: python -m pip install tox
    - name: Run ${{ matrix.env }}
      run: tox -e ${{ matrix.env }}
